import google.generativeai as genai
from config.settings import GEMINI_API_KEY

genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel(
    model_name="gemini-1.5-flash",
    system_instruction="""You are a brilliant personal finance intelligence assistant.
Your job is to write a personalized daily finance newsletter that is:
- Informative but engaging (not dry or overly academic)
- Structured with clear sections
- Written as if by a smart friend who is also a finance expert
- Approximately 10 minutes to read

FORMATTING RULES:
- Use clean HTML for the email (headings, paragraphs, lists)
- Use <h2> for main section headers
- Use <h3> for sub-sections
- Use <p> for body text
- Use <ul>/<li> for bullet lists
- Use <strong> for emphasis
- Use <span style="color:#27ae60"> for positive numbers (green)
- Use <span style="color:#e74c3c"> for negative numbers (red)
- Do NOT use markdown (no ** or ## or -)
- Keep each news summary to 3-4 sentences
- Keep the market briefing factual and concise
- Make the education section your best teaching moment of the day

TONE: Warm, confident, educational. Like a mentor who actually enjoys markets."""
)

def generate_newsletter_with_memory(
    market_text: str,
    news_text: str,
    education_context: str,
    recent_topics: list,
    newsletters_sent: int,
) -> str:

    memory_context = f"""
USER MEMORY CONTEXT:
- Total newsletters received: {newsletters_sent}
- Learning stage: {"early beginner" if newsletters_sent < 14 else "intermediate" if newsletters_sent < 60 else "advanced"}
- Recent topics covered: {', '.join(recent_topics) if recent_topics else 'none yet'}
- Note: {"This is one of their first newsletters — be extra welcoming and encouraging." if newsletters_sent < 3 else ""}
"""

    user_prompt = f"""Write today's complete finance newsletter using the data below.
Include all four sections exactly as specified.

=== LIVE MARKET DATA ===
{market_text}

=== NEWS ARTICLES TO SUMMARIZE ===
{news_text}

=== EDUCATION SECTION BRIEF ===
{education_context}

{memory_context}

=== NEWSLETTER STRUCTURE ===
Write the full newsletter in this exact order:

<h1>📊 Your Daily Finance Intelligence Brief</h1>
<p style="color:#666">[Today's date and a one-sentence market mood summary]</p>

<h2>Section 1: Daily Market Briefing</h2>
[Use the live market data above. Cover indices, yields, crypto, oil, gold.
For each major move (>0.5%), briefly explain the likely cause.
Use green/red color spans for numbers. Keep this under 300 words.]

<h2>Section 2: Top Financial News</h2>
[Summarize the 5-7 most important stories from the articles provided.
For each story include:
- <h3>[Story headline]</h3>
- What happened (1-2 sentences)
- Why it matters for markets/economy
- Potential implications for investors]

<h2>Section 3: Finance Education — [Topic Name]</h2>
[Write the full lesson as specified in the education brief above.]

<h2>Section 4: Your Learning Journey</h2>
[Write 2-3 sentences acknowledging their progress.
Mention what was covered recently and hint at upcoming topics.
End with one reflection question for them to think about today.]

<hr>
<p style="font-size:12px;color:#999">Generated by your personal Finance AI Agent</p>
"""

    response = model.generate_content(user_prompt)
    newsletter_html = response.text

    # Strip markdown code fences if Gemini wraps output in them
    if newsletter_html.startswith("```"):
        newsletter_html = newsletter_html.split("```")[-2] if "```" in newsletter_html else newsletter_html
        newsletter_html = newsletter_html.lstrip("html").strip()

    print(f"✓ Newsletter generated ({len(newsletter_html)} characters)")
    return newsletter_html
