"""
Orchestrator Agent - uses google-genai (new SDK) with gemini-2.0-flash
"""
from google import genai
from google.genai import types
from config.settings import GEMINI_API_KEY

client = genai.Client(api_key=GEMINI_API_KEY)
MODEL = "gemini-2.0-flash"

def build_system_prompt() -> str:
    return """You are a brilliant personal finance intelligence assistant.
Your job is to write a personalized daily finance newsletter that is:
- Informative but engaging (not dry or overly academic)
- Structured with clear sections
- Written as if by a smart friend who is also a finance expert
- Approximately 10 minutes to read

FORMATTING RULES:
- Use clean HTML for the email (headings, paragraphs, lists)
- Use <h2> for main section headers
- Use <h3> for sub-sections
- Use <p> for body text
- Use <ul>/<li> for bullet lists
- Use <strong> for emphasis
- Use <span style="color:#27ae60"> for positive numbers (green)
- Use <span style="color:#e74c3c"> for negative numbers (red)
- Do NOT use markdown (no ** or ## or -)
- Output ONLY raw HTML, no code fences, no backticks

TONE: Warm, confident, educational. Like a mentor who actually enjoys markets."""

def build_user_prompt(market_text, news_text, education_brief) -> str:
    return f"""Write today's complete finance newsletter using the data below.
Include all four sections exactly as specified.

=== LIVE MARKET DATA ===
{market_text}

=== NEWS ARTICLES TO SUMMARIZE ===
{news_text}

=== EDUCATION SECTION BRIEF ===
{education_brief}

=== NEWSLETTER STRUCTURE ===
Write the full newsletter in this exact order:

<h1>Your Daily Finance Intelligence Brief</h1>
<p style="color:#666">[Today's date and a one-sentence market mood summary]</p>

<h2>Section 1: Daily Market Briefing</h2>
[Cover indices, yields, crypto, oil, gold. For each major move over 0.5%, briefly explain the likely cause. Use green/red color spans for numbers. Keep under 300 words.]

<h2>Section 2: Top Financial News</h2>
[Summarize the 5-7 most important stories. For each include:
- <h3>Story headline</h3>
- What happened (1-2 sentences)
- Why it matters for markets
- Implications for investors]

<h2>Section 3: Finance Education</h2>
[Write the full lesson as specified in the education brief above.]

<h2>Section 4: Your Learning Journey</h2>
[2-3 sentences on progress, recent topics, upcoming topics. End with one reflection question.]

<hr>
<p style="font-size:12px;color:#999">Generated by your personal Finance AI Agent</p>
"""

def clean_response(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text[text.index("\n") + 1:] if "\n" in text else text[3:]
    if text.endswith("```"):
        text = text[:text.rfind("```")].strip()
    return text.strip()

def generate_newsletter_with_memory(
    market_text: str,
    news_text: str,
    education_context: str,
    recent_topics: list,
    newsletters_sent: int,
) -> str:
    print(f"Calling Gemini API ({MODEL})...")

    if newsletters_sent < 14:
        learning_stage = "early beginner"
    elif newsletters_sent < 60:
        learning_stage = "intermediate"
    else:
        learning_stage = "advanced"

    memory_context = f"""
USER MEMORY CONTEXT:
- Total newsletters received: {newsletters_sent}
- Learning stage: {learning_stage}
- Recent topics covered: {', '.join(recent_topics) if recent_topics else 'none yet'}
"""

    full_education = education_context + memory_context
    user_prompt = build_user_prompt(market_text, news_text, full_education)

    response = client.models.generate_content(
        model=MODEL,
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=build_system_prompt(),
            max_output_tokens=4096,
        )
    )

    newsletter_html = clean_response(response.text)
    print(f"Newsletter generated ({len(newsletter_html)} characters)")
    return newsletter_html
